name: Test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Run tests
      run: xcodebuild -workspace 'Demo/PopTip Demo.xcworkspace' -scheme 'PopTip Demo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.6' test
